# config/config.yml

# Lista de símbolos a procesar
symbols:
  - EURUSD
  - GBPUSD

# Temporalidades a generar (M1 solo vía HistData; el resto nativo si está soportado)
timeframes:
  - M1
  - M5
  - M15
  - M30
  - H1
  - H4
  - D1

# Espacios de búsqueda para optimización
parameters:
  ema:
    ema_fast: [5, 30]      # Rango para EMA rápida
    ema_slow: [20, 100]    # Rango para EMA lenta
  
  rsi:
    rsi_period: [7, 28]    # Rango para periodo RSI
    oversold: [25, 40]     # Niveles oversold más flexibles
    overbought: [60, 75]   # Niveles overbought más flexibles

data_paths:
  cache: "data/cache"
  raw: "data/raw"
  signals: "senales"

models:
  default_algorithm: "LogisticRegression"
  train_size: 0.8
  random_state: 42
